### ISSUE TITLE
显示出来中间有方框□

### ISSUE THREAD

**Issue by ghmin** [busyboxs/freetype_opencv#2]
我发现一个奇葩的问题，看下图：
[http://www.52play.net/group1/M00/00/05/rBIKaF5YBciAABNMAAAup4zJoYs089.png](bug图)

一个字显示，一个不显示，显示的字左右都有一个方框□护法---是不是字体编码不对还是别的原因？

**Comment by ghmin** [comment]
[bug图片](http://www.52play.net/group1/M00/00/05/rBIKaF5YBciAABNMAAAup4zJoYs089.png)

**Comment by busyboxs** [comment]
@ghmin 这是因为在 windows 下一个汉字占 2 个 字节，在 Linux 下占 3 个字节（绝大部分），所以要在 linux 下运行需要稍微修改一下代码。将 `CvxText.cpp`  第 [120 ~ 121](https://github.com/busyboxs/freetype_opencv/blob/master/opencv_putext_zh/opencv_putext_zh/CvxText.cpp#L120) 行改为以下代码

```cpp
if (!isascii(wc)) {
    mbtowc(&wc, &text[i], 3);
    i += 2;
}
```

**Comment by sunjunlishi** [comment]
> ```c++
> mbtowc(&wc, &text[i], 3);
> ```



> [bug图片](http://www.52play.net/group1/M00/00/05/rBIKaF5YBciAABNMAAAup4zJoYs089.png)



> 我发现一个奇葩的问题，看下图： [http://www.52play.net/group1/M00/00/05/rBIKaF5YBciAABNMAAAup4zJoYs089.png](bug%E5%9B%BE)
> 
> 一个字显示，一个不显示，显示的字左右都有一个方框□护法---是不是字体编码不对还是别的原因？

你最后解决了？@ghmin   我看最终都是 unicode，转为unicode后，显示；
